name: generate snake animation

on:
  schedule:
    - cron: "0 */6 * * *"   # обновление каждые 6 часов
  workflow_dispatch: {}       # + ручной запуск кнопкой "Run workflow"
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: rxdxk
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=%23ffffff&color_dots=%230d0d0d,%23444444,%23888888,%23cccccc,%23ffffff

      - name: push output to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
